name: sharp_work
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  gap:
  flutter_svg:
  flutter_screenutil:
  auto_route:
  get_it:
  hooks_riverpod:
  ficonsax:

  device_preview:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: ^5.9.0
  auto_route_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/ui/shared/constants/

  integrations:
    image: true
    flutter_svg: true
    rive: true
